#FROM maven:3.6.3-openjdk-15 AS build
FROM maven:3.8.3-openjdk-17 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

# FROM adoptopenjdk:15-jre-hotspot
FROM eclipse-temurin:17-jre
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/seznam-api-1.0.0-SNAPSHOT.jar /app
EXPOSE 8081
CMD ["java", "-jar", "seznam-api-1.0.0-SNAPSHOT.jar"]