apiVersion: apps/v1
kind: Deployment
metadata:
  name: seznam-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seznam
  template:
    metadata:
      labels:
        app: seznam
    spec:
      containers:
        - image: bi4528/seznam-slika:latest #to be changed
          name: seznam
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://dumbo.db.elephantsql.com/lwfzuude
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: db-seznam-pass
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: db-seznam-pass
                  key: password
            - name: SEZNAM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: seznam-config
                  key: SEZNAM_SERVICE_URL
          ports:
            - containerPort: 8080
              name: server
#
---

apiVersion: v1
kind: Service
metadata:
  name: seznam
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: seznam

---

