apiVersion: apps/v1
kind: Deployment
metadata:
  name: koktejli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koktejli
  template:
    metadata:
      labels:
        app: koktejli
    spec:
      containers:
        - image: bi4528/koktejli-slika:latest #to be changed
          name: koktejli
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com:5432/eqoftvqn
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: db-elephant-pass
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: db-elephant-pass
                  key: password
            - name: KOKTEJLI_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: koktejli-config
                  key: KOKTEJLI_SERVICE_URL
          ports:
            - containerPort: 8080
              name: server
#          livenessProbe:
#            httpGet:
#              path: /health/live
#              port: server
#            initialDelaySeconds: 20
#            periodSeconds: 3
#          readinessProbe:
#            httpGet:
#              path: /health/ready
#              port: server
#            initialDelaySeconds: 20
#            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: koktejli
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: koktejli