kumuluzee:
  name: koktejli-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/KoktejliMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/koktejli-metadata
      username: dbuser
      password: postgres
#      max-pool-size: 4
      pool:
       max-size: 4
#  health:
#    checks:
#      data-source-health-check:
#        type: liveness
#        jndi-name: jdbc/KoktejliMetadataDS
#    metrics:
#      web-instrumentation:
#        - name: koktejli-endpoint
#          url-pattern: /v1/koktejli/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="37e012f5c11-e21f01-4a1c31-91131b-191521e4816e514bb-ls.logit.io"
                                      port="30014" protocol="udp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'
  rest-properties:
    broken: false
  cors-filter:
    servlet:
      enabled: true
      allow-generic-http-requests: true
      allow-origin: "*"