kumuluzee:
  name: koktejli-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/KoktejliMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/koktejli-metadata
      username: dbuser
      password: postgres
      #max-pool-size: 20
      pool:
       max-size: 4
  dev:
    scan-libraries:
      - seznam-models
      - seznam-services
      - seznam-lib
  openapi-mp:
    ui:
      specification-server: http://34.89.140.13/koktejli/
