kumuluzee:
  name: seznam-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/SeznamMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/seznam-metadata
      username: dbuser
      password: postgres
#      max-pool-size: 4
      pool:
       max-size: 4
  health:
#    checks:
#      data-source-health-check:
#        type: liveness
#        jndi-name: jdbc/SeznamMetadataDS
    metrics:
      web-instrumentation:
        - name: seznam-endpoint
          url-pattern: /v1/seznam/*
      servlet:
        enabled: true
        mapping: /my-metrics-servlet
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="454f7318-e657-4197-b2aa-4ac5b5940747-ls.logit.io"
                                      port="26372" protocol="udp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'
  cors-filter:
    servlet:
      enabled: true
      allow-generic-http-requests: true
      allow-origin: "*"
rest-properties:
  broken: false